export const BEGIN_PANORAMA_DRAG = 'BEGIN_PANORAMA_DRAG';
export const END_PANORAMA_DRAG = 'END_PANORAMA_DRAG';
export const UPDATE_PANORAMA_POSITION = 'UPDATE_PANORAMA_POSITION';
export const MOUSE_ENTER_FLOORPLAN = 'MOUSE_ENTER_FLOORPLAN';
export const MOUSE_LEAVE_FLOORPLAN = 'MOUSE_LEAVE_FLOORPLAN';
export const UPDATE_MOUSE_POSITION = 'UPDATE_MOUSE_POSITION';
